Update template.yml
Added a bit of scaffolding to try detect DBC2CSV failures due to hotfixes and knowing when to try re-run without hotfixes.

diff --git a/.github/workflows/template.yml b/.github/workflows/template.yml
--- a/.github/workflows/template.yml
+++ b/.github/workflows/template.yml
@@ -118,11 +118,30 @@ jobs:
       if: ${{ steps.check.outputs.skip != 'true' }}
       working-directory: extracts/${{ inputs.PRODUCT }}/db2
       run: |
-        ../../../DBC2CSV .
-        if [[ $? -ne 0 && "${{ steps.check.outputs.hotfix }}" == "true" ]]; then
-          rm -f *.bin
-          ../../../DBC2CSV .
+        run_dbc2csv() {
+          local table_count=0
+          local table_count_error=0
+          ../../../DBC2CSV . | tee >(while IFS= read -r line; do
+            if [[ $line == *"Exporting table"* ]]; then
+              (( table_count++ ))
+            elif [[ $line == *"Failed to export"* ]]; then
+              (( table_count_error++ ))
+            fi
+          done)
+          local runExitCode=${PIPESTATUS[0]}
+          local table_count_success=$(( table_count - table_count_error ))
+          echo "$runExitCode,$table_count,$table_count_success,$table_count_error"
+        }
+        output=$(run_dbc2csv)
+        IFS=',' read -r runExitCode table_count table_count_success table_count_error <<< "$output"
+        if [[ "${{ steps.check.outputs.hotfix }}" == "true" ]]; then
+          if [[ $runExitCode -ne 0 || $table_count_success -le $(( table_count / 2 )) ]]; then
+            rm -f *.bin
+            output=$(run_dbc2csv)
+            IFS=',' read -r runExitCode table_count table_count_success table_count_error <<< "$output"
+          fi
         fi
+        echo "DBC2CSV exited with code $runExitCode: $table_count files scanned. $table_count_success converted. $table_count_error failed."
         find . -type f ! -iname "*.csv" -delete
 
     - name: Create branch for release
